---
title: "Twitter_SNA"
output: html_document
reference: https://github.com/ShirinG/blog_posts_prep/blob/master/twitter/twitter_codecentric.Rmd

---

```{r}

library(twitteR)
library(tidyverse)
library(tidytext)
library(ROAuth)
```

```{r}
api_key <- "C4xwHq2EdZ5GL6LaNA6norgUd"

api_secret <- "1UJ4HDznWwTexLmzfu87GyQ01I41D9qugg9pJTwcKUubyZOpvp"

access_token <- "2497530812-8KAYKTo99IuY3bxNPvhARncRr8Eo2GL17GNoeaW"

access_token_secret <- "MXsEF7690Jg1u5S2aN7yLNQwFZKO7CcvizTMZcKBkGmya"

setup_twitter_oauth(api_key, api_secret, access_token, access_token_secret)

```

```{r}
user <- getUser("snowdaylearning")
friends <- user$getFriends()
friends_df <- twListToDF(friends) %>%
  rownames_to_column()
followers <- user$getFollowers() # my followers
followers_df <- twListToDF(followers) %>%
  rownames_to_column()
```
```{r}
friends_followers_df <- rbind(mutate(followers_df, type = ifelse(screenName %in% friends_df$screenName, "friend & follower", "follower")),
      mutate(friends_df, type = ifelse(screenName %in% followers_df$screenName, "friend & follower", "friend"))) %>%
  unique()

```

```{r}
top_influeners <- friends_followers_df %>%
  mutate(date = as.Date(created, format = "%Y-%m-%d"),
         today = as.Date("2018-10-06", format = "%Y-%m-%d"),
         days = as.numeric(today - date),
         statusesCount_pDay = statusesCount / days) %>%
  select(screenName, followersCount, statusesCount_pDay) %>%
  arrange(desc(followersCount)) %>%
  .[1:10, ]

```

```{r}
top_fol <- followers_df %>%
  mutate(date = as.Date(created, format = "%Y-%m-%d"),
         today = as.Date("2018-10-06", format = "%Y-%m-%d"),
         days = as.numeric(today - date),
         statusesCount_pDay = statusesCount / days) %>%
  select(screenName, followersCount, statusesCount_pDay) %>%
  arrange(desc(followersCount)) %>%
  .[1:10, ]

```

```{r}
top_tweet <- followers_df %>%
  mutate(date = as.Date(created, format = "%Y-%m-%d"),
         today = as.Date("2018-10-06", format = "%Y-%m-%d"),
         days = as.numeric(today - date),
         statusesCount_pDay = statusesCount / days) %>%
  select(screenName, followersCount, statusesCount_pDay) %>%
  arrange(desc(statusesCount_pDay)) %>%
  .[1:10, ]

top_fol_tweet <- rbind(top_fol, top_tweet) %>%
  unique()
```

```{r}
followers_df %>%
  mutate(date = as.Date(created, format = "%Y-%m-%d"),
         today = as.Date("2017-06-07", format = "%Y-%m-%d"),
         days = as.numeric(today - date),
         statusesCount_pDay = statusesCount / days) %>%
  ggplot(aes(x = followersCount, y = statusesCount_pDay)) +
    geom_smooth(method = "lm", color = "#377F97") +
    geom_point(color = "#4A9888", alpha = 0.6) +
    #geom_text(data = top_fol_tweet, aes(label = screenName), check_overlap = TRUE, size = 2) +
    scale_x_continuous(trans='log2') +
    scale_y_continuous(trans='log2') +
    theme_bw() +
    labs(x = expression(log[2]~"number of followers"),
         y = expression(log[2]~"average nr. of tweets per day"),
         title = "Codecentric's most influential followers",
         #subtitle = "Text labels show the top 10 followers with most tweets per day and highest number of followers (screen names)",
         caption = expression(2^nd~"degree followers and tweet rate of @snowdaylearning Twitter followers (data from October"~6^th~"2018)"))


```
```{r}

top_fol_2 <- followers_df %>%
  mutate(date = as.Date(created, format = "%Y-%m-%d"),
         today = as.Date("2018-10-06", format = "%Y-%m-%d"),
         days = as.numeric(today - date),
         statusesCount_pDay = statusesCount / days) %>%
  select(screenName, followersCount, statusesCount_pDay) %>%
  mutate(score = followersCount * statusesCount_pDay) %>%
  arrange(desc(score)) %>%
  .[1:100, ]

top_fol_tweet_2 <- top_fol_2 %>%
  left_join(select(followers_df, screenName, description), by = "screenName") %>%
  mutate(id = seq_along(1:n()))

```

```{r}

for (i in 1:length(friends)) {
  friends2 <- friends[[i]]$getFriends() # my friends' friends
  friends2_df <- twListToDF(friends2) %>%
    rownames_to_column() %>%
    mutate(friend = as.character(friends[[i]]$id))
  
  if (i == 1) {
    friends2_df_final <- friends2_df
  } else {
    friends2_df_final <- rbind(friends2_df_final, friends2_df)
  }
  print(i)
}

```
```{r}
install.packages("ggraph")
library(ggraph)
library(igraph)


friends2_df_final <- friends2_df_final %>%
  left_join(select(friends_df, screenName, rowname), by = c("friend" = "rowname"))

edge_table_1 <- data.frame(source = rep("snowdaylearning", nrow(friends_df)),
                         target = friends_df$screenName)

edge_table_2 <- data.frame(source = followers_df$screenName,
                         target = rep("snowdaylearning", nrow(followers_df)))

edge_table_3 <- data.frame(source = friends2_df_final$screenName.y,
                         target = friends2_df_final$screenName.x)

edge_table <- rbind(edge_table_1, edge_table_2, edge_table_3)

graph <- graph_from_data_frame(edge_table, directed = TRUE)
layout <- layout_with_fr(graph)
V(graph)$color <- ifelse(V(graph)$name == "snowdaylearning", "#377F97", "#4A9888")
V(graph)$size <- ifelse(V(graph)$name == "snowdaylearning", 6, 1)
V(graph)$label <- ifelse(V(graph)$name == "snowdaylearning", "snowdaylearning", NA)

pdf("twitter_net.pdf", width = 70, height = 80)
plot(graph,
     layout = layout,
     vertex.label = V(graph)$label,
     vertex.color = scales::alpha(V(graph)$color, alpha = 0.5), 
     vertex.size = V(graph)$size , 
     vertex.frame.color = "gray", 
     vertex.label.color = "black", 
     vertex.label.cex = 10,
     edge.arrow.size = 1)
dev.off()

```


```{r}
betweenness <- igraph::betweenness(graph, directed = TRUE)
#betweenness[order(betweenness, decreasing = TRUE)]
edge_betweenness <- igraph::edge_betweenness(graph, directed = TRUE)

V(graph)$size <- ifelse(V(graph)$name == "snowdaylearning", 10, betweenness * 0.000001)

plot(graph,
     layout = layout,
     vertex.label = V(graph)$label,
     vertex.color = scales::alpha(V(graph)$color, alpha = 0.5), 
     vertex.size = V(graph)$size, 
     vertex.frame.color = "gray", 
     vertex.label.color = "black", 
     vertex.label.cex = 6,
     edge.width = edge_betweenness * 0.0000001,
     edge.arrow.size = 1)
dev.off()
```